packing_list_api:
  resource: "@EvrinomaPackingListBundle/Controller/PackingListApiController.php"
  type: annotation

packing_list_item_api:
  resource: "@EvrinomaPackingListBundle/Controller/ListItemApiController.php"
  type: annotation

packing_depart_api:
  resource: "@EvrinomaPackingListBundle/Controller/DepartApiController.php"
  type: annotation

packing_logistics_api:
  resource: "@EvrinomaPackingListBundle/Controller/LogisticsApiController.php"
  type: annotation

packing_list_group_api:
  resource: "@EvrinomaPackingListBundle/Controller/PackingListGroupApiController.php"
  type: annotation