imports:
  - { resource: constraint/packing_list.yml }
  - { resource: constraint/list_item.yml }
  - { resource: constraint/depart.yml }
  - { resource: constraint/logistics.yml }
  - { resource: constraint/packing_list_group.yml }
  - { resource: constraint/group.yml }
  - { resource: constraint/logistics_group.yml }